### ISSUE TITLE
instantmeshrun error

### ISSUE THREAD

**Issue by webcoderz** [jtydhr88/ComfyUI-InstantMesh#12]
hi this is a cool package and i like that you're responding quickly:

i have an error i am seeing when running your gypsum run:

i have installed comfy-3d and it runs with other flows.. when trying to do your demo workflow with gypsum i am getting this error:
```
comfy-3d-1      | [1/1] Creating InstantMesh_20240422_170553 ...
comfy-3d-1      | !!! Exception during processing!!! operands could not be broadcast together with shapes (320,320,3,6) (3,) 
comfy-3d-1      | Traceback (most recent call last):
comfy-3d-1      |   File "/app/execution.py", line 151, in recursive_execute
comfy-3d-1      |     output_data, output_ui = get_output_data(obj, input_data_all)
comfy-3d-1      |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
comfy-3d-1      |   File "/app/execution.py", line 81, in get_output_data
comfy-3d-1      |     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
comfy-3d-1      |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
comfy-3d-1      |   File "/app/execution.py", line 74, in map_node_over_list
comfy-3d-1      |     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
comfy-3d-1      |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
comfy-3d-1      |   File "/app/custom_nodes/ComfyUI-InstantMesh/run.py", line 394, in run
comfy-3d-1      |     preview_img_path, mesh_path_idx, video_path_idx = run_InstantMesh(
comfy-3d-1      |                                                       ^^^^^^^^^^^^^^^^
comfy-3d-1      |   File "/app/custom_nodes/ComfyUI-InstantMesh/run.py", line 252, in run_InstantMesh
comfy-3d-1      |     planes = model.forward_planes(images, input_cameras)
comfy-3d-1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
comfy-3d-1      |   File "/app/custom_nodes/ComfyUI-InstantMesh/src/models/lrm_mesh.py", line 94, in forward_planes
comfy-3d-1      |     image_feats = self.encoder(images, cameras)
comfy-3d-1      |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
comfy-3d-1      |   File "/home/user/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
comfy-3d-1      |     return self._call_impl(*args, **kwargs)
comfy-3d-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
comfy-3d-1      |   File "/home/user/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
comfy-3d-1      |     return forward_call(*args, **kwargs)
comfy-3d-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
comfy-3d-1      |   File "/app/custom_nodes/ComfyUI-InstantMesh/src/models/encoder/dino_wrapper.py", line 44, in forward
comfy-3d-1      |     inputs = self.processor(
comfy-3d-1      |              ^^^^^^^^^^^^^^^
comfy-3d-1      |   File "/home/user/.local/lib/python3.11/site-packages/transformers/image_processing_utils.py", line 446, in __call__
comfy-3d-1      |     return self.preprocess(images, **kwargs)
comfy-3d-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
comfy-3d-1      |   File "/home/user/.local/lib/python3.11/site-packages/transformers/models/vit/image_processing_vit.py", line 271, in preprocess
comfy-3d-1      |     images = [self.normalize(image=image, mean=image_mean, std=image_std) for image in images]
comfy-3d-1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
comfy-3d-1      |   File "/home/user/.local/lib/python3.11/site-packages/transformers/models/vit/image_processing_vit.py", line 271, in <listcomp>
comfy-3d-1      |     images = [self.normalize(image=image, mean=image_mean, std=image_std) for image in images]
comfy-3d-1      |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
comfy-3d-1      |   File "/home/user/.local/lib/python3.11/site-packages/transformers/models/vit/image_processing_vit.py", line 181, in normalize
comfy-3d-1      |     return normalize(image, mean=mean, std=std, data_format=data_format, **kwargs)
comfy-3d-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
comfy-3d-1      |   File "/home/user/.local/lib/python3.11/site-packages/transformers/image_transforms.py", line 349, in normalize
comfy-3d-1      |     image = ((image.T - mean) / std).T
comfy-3d-1      |               ~~~~~~~~^~~~~~
comfy-3d-1      | ValueError: operands could not be broadcast together with shapes (320,320,3,6) (3,) 
comfy-3d-1      | 
comfy-3d-1      | Prompt executed in 383.71 seconds
comfy-3d-1      | no pending upload
```

**Comment by webcoderz** [comment]
nvm updated and works <3
