### ISSUE TITLE
getting error when downloading models.

### ISSUE THREAD

**Issue by RYG81** [jtydhr88/ComfyUI-InstantMesh#4]
Error occurred when executing InstantMeshRun:

[Errno 28] No space left on device

File "D:\000AI\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-InstantMesh\run.py", line 400, in run
preview_img_path, mesh_path_idx, video_path_idx = run_InstantMesh(
^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-InstantMesh\run.py", line 158, in run_InstantMesh
pipeline = DiffusionPipeline.from_pretrained(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 671, in from_pretrained
cached_folder = cls.download(
^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1406, in download
cached_folder = snapshot_download(
^^^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\_snapshot_download.py", line 308, in snapshot_download
thread_map(
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map
return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map
return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\tqdm\std.py", line 1181, in __iter__
for obj in iterable:
File "concurrent\futures\_base.py", line 619, in result_iterator
File "concurrent\futures\_base.py", line 317, in _result_or_cancel
File "concurrent\futures\_base.py", line 456, in result
File "concurrent\futures\_base.py", line 401, in __get_result
File "concurrent\futures\thread.py", line 58, in run
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\_snapshot_download.py", line 283, in _inner_hf_hub_download
return hf_hub_download(
^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1457, in hf_hub_download
http_get(
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 527, in http_get
temp_file.write(chunk)
File "tempfile.py", line 483, in func_wrapper

**Comment by RYG81** [comment]
i see its downloading model in C, but have no space. Can you make it download to custom node folder?

**Comment by RYG81** [comment]
!!! Exception during processing !!!:  21%|████████████████▌                                                              | 724M/3.46G [05:20<21:24, 2.13MB/s]
Traceback (most recent call last):s:  41%|████████████████████████████████▎                                             | 1.44G/3.46G [07:30<05:59, 5.64MB/s]
  File "D:\000AI\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute                                          | 1.53G/3.46G [07:39<02:59, 10.7MB/s]
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-InstantMesh\run.py", line 400, in run
    preview_img_path, mesh_path_idx, video_path_idx = run_InstantMesh(
                                                      ^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-InstantMesh\run.py", line 158, in run_InstantMesh
    pipeline = DiffusionPipeline.from_pretrained(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 671, in from_pretrained
    cached_folder = cls.download(
                    ^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1406, in download
    cached_folder = snapshot_download(
                    ^^^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\_snapshot_download.py", line 308, in snapshot_download
    thread_map(
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "concurrent\futures\_base.py", line 619, in result_iterator
  File "concurrent\futures\_base.py", line 317, in _result_or_cancel
  File "concurrent\futures\_base.py", line 456, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\_snapshot_download.py", line 283, in _inner_hf_hub_download
    return hf_hub_download(
           ^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1457, in hf_hub_download
    http_get(
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 552, in http_get
    raise EnvironmentError(
OSError: Consistency check failed: file should be of size 3463726504 but has size 1531330968 (diffusion_pytorch_model.safetensors).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.

still getting error even though i made 15 Gb space in C

**Comment by jtydhr88** [comment]
Hi, since the logic of downloading checkpoint comes from huggingface lib, I will investigate how to modify the download folder later this week

**Comment by RYG81** [comment]
OK bro,
https://thinkinfi.com/huggingface-download-and-save-model-to-custom-path/
this may help
